version: "3.9"
services:
  expressapp:
    container_name: expressapp
    build: ./backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
    command: ["npm", "start"]

  reactapp:
    container_name: reactapp
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "8081:80"
    links:
      - expressapp
      - reactapp
    restart: always
