# Dockerfile para expressapp
FROM node:14

# Establecer el directorio de trabajo en el contenedor
WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Exponer el puerto en el que la aplicación estará corriendo
EXPOSE 3001

# Comando para iniciar la aplicación
CMD ["npm", "start"]